#!/usr/bin/env python3
"""Exercise the asset-group compiler with a tiny non-rack Blender library.

Creates its inputs and binaries in ignored .local/export-fixture. The checked-in
evidence records actual source ancestry, USD metadata and manifest consistency.
No server-rack names, source files or recipe defaults participate in the check.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BLENDER = "/Applications/Blender.app/Contents/MacOS/Blender"


def write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2) + "\n")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def create_fixture(directory: Path) -> None:
    import bpy
    from mathutils import Vector

    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    source = bpy.data.collections.new("Desk lamp components")
    bpy.context.scene.collection.children.link(source)

    def move_to_source(obj, name, part_id, parent=None):
        obj.name = name
        obj["part_id"] = part_id
        obj["evidence_level"] = "synthetic_fixture"
        for collection in list(obj.users_collection):
            collection.objects.unlink(obj)
        source.objects.link(obj)
        if parent is not None:
            obj.parent = parent
        return obj

    root = bpy.data.objects.new("DeskLampRoot", None)
    source.objects.link(root)
    root["part_id"] = "fixture.lamp"
    root.location = (0.12, -0.08, 0.02)

    bpy.ops.mesh.primitive_cube_add(size=1)
    base = move_to_source(bpy.context.object, "WeightedBase", "fixture.base", root)
    base.scale = (0.24, 0.16, 0.04)
    base.location = (0, 0, 0.02)

    stem_root = bpy.data.objects.new("StemAssembly", None)
    source.objects.link(stem_root)
    stem_root["part_id"] = "fixture.stem_assembly"
    stem_root.parent = root
    stem_root.location = (0, 0, 0.04)
    bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=0.012, depth=0.3)
    stem = move_to_source(
        bpy.context.object, "StemTube", "fixture.stem_tube", stem_root
    )
    stem.location = (0, 0, 0.15)
    bpy.ops.mesh.primitive_cube_add(size=1)
    collar = move_to_source(
        bpy.context.object, "StemCollar", "fixture.stem_collar", stem_root
    )
    collar.scale = (0.04, 0.04, 0.03)
    collar.location = (0, 0, 0.285)

    bpy.ops.mesh.primitive_cone_add(vertices=12, radius1=0.1, radius2=0.04, depth=0.12)
    shade = move_to_source(bpy.context.object, "LampShade", "fixture.shade", root)
    shade.location = (0, 0, 0.4)
    bpy.context.scene.unit_settings.system = "METRIC"
    bpy.context.scene.unit_settings.scale_length = 1
    bpy.context.view_layer.update()
    library = directory / "desk-lamp.blend"
    bpy.ops.wm.save_as_mainfile(filepath=str(library), check_existing=False)
    groups = [
        ("base", "Weighted base", ["fixture.base"]),
        ("stem", "Stem assembly", ["fixture.stem_assembly"]),
        ("shade", "Lamp shade", ["fixture.shade"]),
    ]
    recipe = {
        "schema": "astra-asset-group-recipe/v1",
        "source": {
            "path": ".local/export-fixture/desk-lamp.blend",
            "sha256": sha256(library),
            "provenance": "Synthetic acceptance fixture generated by check-asset-group-compiler.py",
        },
        "templateID": "desk-lamp",
        "rootEntityName": "DeskLamp",
        "collections": ["Desk lamp components"],
        "partIDPrefix": "lamp.",
        "fallbackGroup": "base",
        "groups": [
            {
                "id": identifier,
                "name": name,
                "description": name + " from a synthetic desk lamp.",
                "representation": "synthetic_fixture",
                "triangleBudget": 200,
                "ancestorPartIDs": ancestors,
            }
            for identifier, name, ancestors in groups
        ],
        "coordinates": {
            "units": "meters",
            "sourceUpAxis": "Z",
            "sourceOrigin": "Fixture world origin, including nonzero source-root translation.",
        },
        "limits": [
            "Synthetic geometry tests compiler invariants, not hardware realism or native rendering performance."
        ],
    }
    write_json(directory / "recipe.json", recipe)
    expectations = {}
    for identifier, objects in [
        ("base", [base]),
        ("stem", [stem, collar]),
        ("shade", [shade]),
    ]:
        points = [
            obj.matrix_world @ Vector(corner)
            for obj in objects
            for corner in obj.bound_box
        ]
        expectations["lamp." + identifier] = {
            "sourcePartIDs": sorted(obj["part_id"] for obj in objects),
            "minimum": [min(point[axis] for point in points) for axis in range(3)],
            "maximum": [max(point[axis] for point in points) for axis in range(3)],
        }
    write_json(directory / "expected.json", expectations)


def verify_fixture(directory: Path, evidence_path: Path) -> None:
    from pxr import Usd, UsdGeom

    manifest = json.loads((directory / "manifest.json").read_text())
    catalog = json.loads((directory / "desk-lamp.catalog.json").read_text())
    index = json.loads((directory / "source-index.json").read_text())
    expected = json.loads((directory / "expected.json").read_text())
    build = json.loads((directory / "build.json").read_text())
    recipe = json.loads((directory / "recipe.json").read_text())
    output = directory / "desk-lamp.usdz"
    source = directory / "desk-lamp.blend"
    assert manifest["templateID"] == "desk-lamp"
    assert manifest["hierarchy"]["rootID"] == "desk-lamp"
    assert set(manifest["hierarchy"]["children"]) == set(expected)
    assert catalog["sha256"] == sha256(output)
    assert catalog["assetID"] == "sha256:" + sha256(output)
    assert catalog["byteCount"] == output.stat().st_size
    assert recipe["source"]["sha256"] == sha256(source)
    assert index["sourceSHA256"] == sha256(source)
    stage = Usd.Stage.Open(str(output))
    assert stage is not None
    assert str(UsdGeom.GetStageUpAxis(stage)) == "Z"
    assert UsdGeom.GetStageMetersPerUnit(stage) == 1
    all_prims = list(stage.TraverseAll())
    triangles = sum(
        sum(
            max(0, int(count) - 2)
            for count in UsdGeom.Mesh(prim).GetFaceVertexCountsAttr().Get()
        )
        for prim in all_prims
        if prim.IsA(UsdGeom.Mesh)
    )
    assert (
        triangles
        == catalog["uniqueTriangleCount"]
        == sum(part["triangleCount"] for part in manifest["parts"])
    )
    validated_parts = []
    for part in manifest["parts"]:
        part_id = part["partID"]
        assert part["parentTemplateID"] == "desk-lamp"
        assert part["representation"] == "synthetic_fixture"
        source_ids = sorted(row["partID"] for row in index["parts"][part_id])
        assert source_ids == expected[part_id]["sourcePartIDs"]
        assert part["sourceObjectCount"] == len(source_ids)
        assert 0 < part["triangleCount"] <= 200
        matches = [
            prim for prim in all_prims if str(prim.GetName()) == part["entityName"]
        ]
        assert len(matches) == 1
        for side in ["minimum", "maximum"]:
            assert (
                max(
                    abs(a - b)
                    for a, b in zip(
                        part["sourceBoundsMeters"][side], expected[part_id][side]
                    )
                )
                < 1e-6
            )
        validated_parts.append(
            {
                "partID": part_id,
                "parentTemplateID": part["parentTemplateID"],
                "entityName": part["entityName"],
                "sourcePartIDs": source_ids,
                "triangleCount": part["triangleCount"],
                "sourceBoundsMeters": part["sourceBoundsMeters"],
            }
        )
    write_json(
        evidence_path,
        {
            "schema": "astra-asset-group-compiler-check/v1",
            "status": "passed",
            "command": "python3 tools/checks/check-asset-group-compiler.py",
            "fixture": "Synthetic desk lamp with three semantic groups and a nested stem assembly; no rack source or recipe is used.",
            "compiler": "tools/assets/export-asset-groups.py",
            "blenderVersion": build["blenderVersion"],
            "sourceSHA256": sha256(source),
            "outputSHA256": sha256(output),
            "bytes": output.stat().st_size,
            "triangleCount": triangles,
            "exportedUpAxis": str(UsdGeom.GetStageUpAxis(stage)),
            "metersPerUnit": UsdGeom.GetStageMetersPerUnit(stage),
            "checks": [
                "Explicit non-rack recipe accepted",
                "Nested source ancestry resolves to the requested semantic group",
                "Source part IDs retained in source index",
                "All manifest parents reference the declared template",
                "Unique semantic USD entity roots retained",
                "World bounds preserve ancestor translation",
                "USD and manifest triangle totals agree",
                "SHA256 catalog addresses exact exported bytes",
                "Source library remains unchanged",
            ],
            "parts": validated_parts,
            "nativeLoadVerified": False,
            "limitations": [
                "This check validates compilation and OpenUSD parsing, not RealityKit loading, visual fidelity or device performance."
            ],
        },
    )
    print(
        f"Asset group compiler fixture passed: {len(validated_parts)} parts, {triangles} triangles.",
        flush=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--blender", default=DEFAULT_BLENDER)
    parser.add_argument(
        "--directory", type=Path, default=ROOT / ".local/export-fixture"
    )
    parser.add_argument(
        "--evidence", type=Path, default=ROOT / "docs/evidence/asset-group-fixture.json"
    )
    parser.add_argument("--stage", choices=["create", "verify"])
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else sys.argv[1:]
    args = parser.parse_args(argv)
    args.directory.mkdir(parents=True, exist_ok=True)
    if args.stage == "create":
        create_fixture(args.directory)
        return 0
    if args.stage == "verify":
        verify_fixture(args.directory, args.evidence)
        return 0
    base = [
        args.blender,
        "--background",
        "--factory-startup",
        "--python-exit-code",
        "1",
        "--python",
        str(Path(__file__).resolve()),
        "--",
        "--directory",
        str(args.directory),
        "--evidence",
        str(args.evidence),
    ]
    subprocess.run([*base, "--stage", "create"], check=True)
    subprocess.run(
        [
            sys.executable,
            str(ROOT / "tools/assets/export-asset-groups.py"),
            "--blender",
            args.blender,
            "--recipe",
            str(args.directory / "recipe.json"),
            "--input",
            str(args.directory / "desk-lamp.blend"),
            "--output",
            str(args.directory / "desk-lamp.usdz"),
            "--manifest",
            str(args.directory / "manifest.json"),
            "--evidence",
            str(args.directory / "build.json"),
            "--index",
            str(args.directory / "source-index.json"),
        ],
        check=True,
    )
    subprocess.run([*base, "--stage", "verify"], check=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
