"""Build source-linked component metadata; no Blender/scene mutations."""
from pathlib import Path
import json,re,datetime,hashlib
ROOT=Path(__file__).resolve().parents[2]
R=ROOT/'research/components'; OCP=ROOT.parent/'research/ocp-candidates'
BOM=OCP/'inspection/evt-bom-primary-items.json'
PLAC=OCP/'inspection/evt-odb-placement-bom.json'
SCH=OCP/'inspection/extracted/zaius-EVT/ZAIUS-MB-EVT3-HW-SCH-X01_20161226_0900.pdf'
SPEC=OCP/'originals/zaius-barreleye-g2/specs/Barreleye G2 - Zaius OCP HW Spec V0.9.0 06102018.pdf'
WB=OCP/'originals/zaius-barreleye-g2/HW/EE/BoM/EVT/ZAIUS-MB-EVT3-HW-EBOM-X00_20161228-add_2nd_source_X15-20170106-Final.xls'
def rel(p):return str(p.relative_to(ROOT)) if p.is_relative_to(ROOT) else '../'+str(p.relative_to(ROOT.parent))
def source(p,**kw):return {'path':rel(p),**kw}
def doc(n,p):return source(R/'originals'/(n+'.pdf'),page_1based=p)
def slug(s):return re.sub('[^a-z0-9]+','-',s.lower()).strip('-')
def classify(s):
 d=s.lower()
 for keys,t,fn in [(['pcb,'],'pcb','Carries patterned copper interconnect and mounted components.'),(['power9 cpu socket'],'cpu_socket','Provides the removable processor module electrical and mechanical interface.'),(['conn,ddr'],'memory_socket','Connects and retains a removable DDR4 memory module.'),(['dram,'],'dram','Stores volatile data used by its attached controller.'),(['flash,'],'flash_memory','Stores data without power; exact firmware role follows the schematic.'),(['eeprom,'],'eeprom','Stores electrically erasable nonvolatile configuration data.'),(['cap,','ecap,','spet cap','spea cap','sp-cap'],'capacitor','Stores electric charge; exact circuit role depends on its connected nets.'),(['res,'],'resistor','Sets resistance; circuit use may be biasing, termination, sensing or configuration.'),(['ind,'],'inductor','Stores magnetic energy; circuit role depends on connected nets.'),(['ferrite','bead'],'ferrite_bead','Adds frequency-dependent impedance for interference suppression.'),(['mos n','mos p'],'mosfet','Switches or controls current through a semiconductor channel.'),(['diode'],'diode','Provides direction-dependent conduction or protection according to circuit placement.'),(['conn,'],'connector','Provides a separable electrical interface.'),(['converter,'],'power_converter','Changes electrical supply voltage; actual rail identified by schematic.'),(['fuse,'],'fuse','Opens the current path when its specified overcurrent conditions occur.'),(['battery,'],'battery','Provides backup electrical energy.'),(['crystal','oscillator'],'clock_source','Provides a timing reference.'),(['ic,regulator'],'voltage_regulator','Regulates a supply rail.'),(['ic,pwm controller'],'pwm_controller','Controls a switched power stage; exact part function may differ from BOM shorthand.'),(['ic,'],'integrated_circuit','Electronic subsystem; exact role requires its device documentation and board nets.')]:
  if any(k in d for k in keys):return t,fn
 return 'board_component','Board component identified by the EVT3 BOM; detailed operation has not been resolved.'
rows=json.loads(BOM.read_text());placements=json.loads(PLAC.read_text());lib={};by_mpn={}
for row in rows:
 typ,fn=classify(row['description']);mpn=row['manufacturer_part'];k='::'.join([typ,slug(row['manufacturer']),mpn])
 if k not in lib:
  lib[k]={'component_key':k,'semantic_type':typ,'display_name':row['description'],'manufacturer':row['manufacturer'],'manufacturer_part_number':mpn,'configuration':'Zaius motherboard EVT3','function':fn,'how_it_works':'Category-level explanation only; consult board connections for the role of this occurrence.','internal_parts':[],'evidence_level':{'identity':'documented_EVТ3_BOM','function':'category_inference','geometry':'not_resolved','internal_structure':'not_resolved'},'sources':[],'refdes':[],'bom_rows':[],'origins':{'identity':'Official OCP Zaius-Barreleye G2 EVT3 PWA BOM','geometry':'EDA placements retain native board origin; scene transform must be recorded by integrator','asset_origin_policy':'Use source component origin when available; do not silently center or mirror assemblies'},'training_context':'Identify this part at its source refdes; do not treat a BOM item as proof it is installed in a physical specimen.','uncertainties':['Primary BOM item; manufacturing population must be joined per occurrence.','No fabrication serial, lot code or live state is supplied.']}
 by_mpn[mpn]=k;rec=lib[k];rec['refdes']+=row['locations'].split(',');rec['bom_rows'].append(row['source_row']);rec['sources'].append(source(WB,sheet='PWA BOM',row_1based=row['source_row']))

def enrich(mpn,typ,title,fn,how,parts,refs,geometry=None,uncertainties=None):
 rec=lib[by_mpn[mpn]];rec.update(semantic_type=typ,display_name=title,function=fn,how_it_works=how,internal_parts=[{'name':x,'representation':'functional explanatory block; not exact silicon or hidden construction'} for x in parts]);rec['sources']+=refs;rec['evidence_level']['function']='documented_board_or_manufacturer';rec['training_context']=fn+' Select source refdes for installed-board context.'
 if geometry:rec['geometry_constraints']=geometry;rec['evidence_level']['geometry']='documented_dimensions_or_EDA_envelope_as_labeled'
 if uncertainties:rec['uncertainties']+=uncertainties
 return rec
s=lambda p:source(SCH,page_1based=p,sheet_1based=p)
enrich('PE38993-51BC0-1H','cpu_socket','Foxconn POWER9 LGA3899 hybrid socket','Clamps and connects a POWER9 LaGrange module to the board.','Compliant socket contacts mate to lands on the processor package; retention and heatsink loading maintain contact.',['contact array','insulating housing','retention structure'],[s(11),doc('power9-lagrange-v1.7',77)],{'contact_count':3899,'package_mating_body_mm':[68.5,68.5],'contact_pitch_mm':1.016,'lattice':'hexagonal, per processor datasheet'},['Module dimensions are not socket external dimensions. Use EVT mechanical CAD for exact socket retention shape.'])
enrich('AST2500A2-GP','bmc','ASPEED AST2500 management processor','Runs the server management computer alongside the POWER9 host.','Uses dedicated DDR4 and firmware storage; connects to host control buses, sensors and management networking.',['ARM11 CPU','DDR controller','Ethernet MAC','GPIO and I2C interfaces','video and remote console functions'],[s(141),s(143),source(SPEC,page_1based=23),{'url':'https://www.aspeedtech.com/server_ast2500/','locator':'AST2500 product overview'}],None,['BMC independence requires standby power and working management path; no live BMC has been tested.'])
enrich('MT40A512M16JY-083E:B','bmc_dram','Micron 8Gb x16 BMC DDR4 SDRAM','Supplies 1GB of volatile working memory to the BMC.','BMC DDR4 interface addresses DRAM banks and transfers data on both clock edges; stored charge requires refresh.',['memory cell arrays','row/column selection','sense amplifiers','I/O interface'],[s(142)],{'package':'96-ball FBGA','dimensions':'Use EVT package envelope; exact manufacturer outline for this revision not acquired.'},['This soldered U17 is not one of the host RDIMM modules. Internal DRAM-cell layout is explanatory only.'])
enrich('BCM54612EB1KMLG','ethernet_phy','Broadcom BCM54612E management Ethernet PHY','Converts the BMC Ethernet interface to the external copper Ethernet link.','RGMII carries digital data to the PHY; analog line signaling passes through the network connector.',['RGMII interface','PHY transmit/receive circuits','clock interface'],[s(140)],None,['Sheet140 connects bottom PortA to this PHY; top PortB is BCM5719. Do not infer both ports are independent host NICs.'])
enrich('BCM5719A1KFBG','ethernet_controller','Broadcom BCM5719 host LAN controller','Provides the board host Ethernet controller and management sideband capability.','PCIe host transfers feed Ethernet MAC/PHY circuitry; NC-SI provides a management sideband interface.',['PCIe interface','Ethernet MAC/PHY blocks','packet buffer','NC-SI interface'],[s(135),s(136),s(140),doc('broadcom-bcm5719',1)],None,['Four-port chip capability does not establish four exposed RJ45 ports on this board.'])
enrich('UCD90160RGCR-C09','power_sequencer','TI UCD90160 16-rail sequencer and monitor','Monitors power rails and coordinates their enable sequence.','ADC measurements and programmable dependencies govern GPIO enables, status and fault handling.',['ADC','GPIO','sequencing logic','PMBus interface'],[s(168),doc('ti-ucd90160',1),doc('ti-ucd90160',52)],{'body_nominal_mm':[9,9],'height_max_mm':1,'terminal_pitch_mm':0.5,'package':'RGC0064B VQFN64'},['C09 board-programmed suffix preserved; do not imply downloaded generic datasheet supplies board configuration.'])
enrich('ISL68137IRAZ-EVT3','pwm_controller','Intersil ISL68137 configurable PWM controller','Controls the voltage-regulation loop in the board power subsystem.','Measures feedback and generates PWM commands; PMBus and AVSBus communicate settings and telemetry.',['digital feedback controller','PWM outputs','PMBus','AVSBus'],[s(179),doc('renesas-isl68137',1),doc('renesas-isl68137',54)],{'body_nominal_mm':[6,6],'height_max_mm':1,'terminal_pitch_mm':0.4,'package':'48-lead QFN'},['BOM manufacturer-part field is ISL68137IRAZ-EVT3; description says ISL68137IRAZ-T. Preserve suffix distinction.'])
enrich('VTM48MP012T130AA0','current_multiplier','Vicor VTM current multiplier','Provides low-voltage high-current power near the CPU load.','A resonant fixed-ratio converter works with an upstream regulator; ratio K=1/40.',['resonant conversion stage','current monitor','temperature monitor','enable input'],[s(181),doc('vicor-vtm48mp012t130aa0',1),doc('vicor-vtm48mp012t130aa0',2)],{'package':'1323 ChiP','body_mm':[13.49,22.5,4.5],'body_source_url':'https://www.vicorpower.com/products?productKey=VTM48MP012T130AA0&productType=cfg'},['Do not use generic buck-inductor topology to claim exact internal Vicor construction. Body dimensions from manufacturer web page, not dimensioned PDF outline.'])
for m in ['VTM48RP015C076AG0','VTM48MP010C105AG0']:
 enrich(m,'current_multiplier','Vicor '+m,'Transforms board power to a load rail.','VTM device paired with upstream regulator in factorized board power architecture.',['power conversion module'],[s(4)],None,['Exact internal topology and body outline for this MPN not independently acquired.'])
for m in ['PI3753-00-LGIZ','PI3755-02-LGIZ']:
 enrich(m,'pre_regulator','Vicor '+m,'Regulates the supply feeding a VTM conversion stage.','Board power map pairs a regulator stage with the VTM near a CPU or memory rail.',['regulator block'],[s(4)],None,['Power-map part suffixes differ from final BOM in places; BOM retained as identity authority.'])
enrich('INA194AIDBVR','current_sensor','TI INA194 current-sense amplifier','Reports a signal proportional to the sensed current.','Amplifies the voltage drop across a current-sense resistor.',['differential amplifier'],[s(180)],None,['Exact gain and channel wiring should be read from its detailed datasheet before simulation.'])
enrich('42819-4233','power_connector','Molex Mini-Fit Sr 48V input header','Connects 48V input, enable and return to the motherboard.','Four mating circuits with paired board solder tails connect the latched input cable.',['black molded housing','four mating contacts','paired solder tails','retention clips'],[s(250),{'url':'https://www.molex.com/en-us/products/series-chart/42819','locator':'428194233'}],{'mating_circuits':4,'mating_rows':1,'pitch_mm':10,'body_length_mm':40.9},['BOM describes 2X4 and DIP8; actual mating connector is four-circuit single-row per manufacturer and schematic.'])
for m,color in [('10140702-0302K11LF','blue'),('10140702-0301K11LF','black')]:
 enrich(m,'memory_socket','FCI DDR4 DIMM socket ('+color+')','Retains and connects a host DDR4 RDIMM.','Keyed card edge and end latches locate the module; socket contacts connect 288 module fingers.',['housing','key','end retention latches','contact array'],[source(SPEC,page_1based=18)],{'contacts':288,'contact_pitch_mm':0.85,'color':color,'adjacent_socket_pitch_mm':8.636},['Socket dimensions and placement from native EVT CAD/ODB. Host module manufacturer is unspecified.'])
enrich('1840855-5','network_connector','TRP stacked dual RJ45 network connector','Exposes the documented host and management Ethernet ports.','PortA bottom connects management PHY; PortB top connects BCM5719.',['two RJ45 cavities','contacts','LEDs','shield'],[s(140)],None,['Do not confuse RJ45-shaped serial console with Ethernet on the other I/O assembly.'])
enrich('MX66L51235FMI-10G','flash_memory','Macronix 512Mb SPI flash','Provides nonvolatile firmware storage.','SPI commands read and write flash arrays; separate device instances serve board firmware roles.',['flash array','SPI controller'],[s(144)],None,['U20/U21 roles must follow corresponding schematic nets; no firmware bytes acquired.'])
enrich('PCF8523TK','rtc','NXP PCF8523 real-time clock','Keeps calendar/time information for management.','Clock oscillator and counters communicate over I2C.',['oscillator','calendar counters','I2C interface'],[source(SPEC,page_1based=23)],None,['No actual time setting or backup battery state is modeled.'])
enrich('0101EJD00-000-G','pcb','GCE Zaius EVT3 motherboard','Mechanically supports components and routes signal/power layers.','A multilayer copper/dielectric stack carries power, ground and high-speed interconnect.',['22-layer stack','copper traces and planes','vias','solder mask','silkscreen'],[source(SPEC,page_1based=21),source(SPEC,page_1based=22)],None,['BOM says red OSP 22-layer PCB. Exact artwork can come from matching EVT fabrication data; decorative random traces are not evidence.'])
# Non-BOM assemblies are explicit design contexts and cannot be mistaken for installed BOM parts.
def context(key,typ,name,mfg,mpn,fn,how,parts,refs,geom=None,unc=None):
 lib[key]={'component_key':key,'semantic_type':typ,'display_name':name,'manufacturer':mfg,'manufacturer_part_number':mpn,'configuration':'training context / selected platform family','function':fn,'how_it_works':how,'internal_parts':parts,'sources':refs,'refdes':[],'evidence_level':{'identity':'platform_family_or_explicit_analogue','function':'documented_principle','geometry':'documented_where_labeled','internal_structure':'explanatory'},'origins':{'identity':'Context record, not a PWA BOM component','asset_origin_policy':'Parent assembly frame; integrator must record actual transform'},'training_context':fn,'uncertainties':unc or []}
 if geom:lib[key]['geometry_constraints']=geom
context('processor::ibm::power9-lagrange','processor','IBM POWER9 LaGrange processor module','IBM',None,'Executes host workloads and connects memory and high-speed I/O.','CPU cores execute instructions; caches reduce memory traffic; on-chip controllers communicate with DIMMs and devices.',['organic package substrate','3899 land interface','silicon die','cores/cache/interconnect as explanatory blocks'],[doc('power9-lagrange-v1.7',77),doc('power9-lagrange-v1.7',16),doc('power9-hotchips2016',4),doc('power9-hotchips2016',7),source(SPEC,page_1based=18)],{'body_mm':[68.5,68.5],'land_count':3899,'land_pitch_mm':1.016,'land_lattice':'hexagonal','substrate_construction':'7-2-7 organic'},['CPU ordering code, enabled core count and stepping are unspecified.','Full separate LaGrange thermal/mechanical guide was referenced but not acquired.','IBM die illustration supports floorplan explanation, not exact transistor layout or package die orientation.','General Hot Chips chip capability differs from specific LaGrange package I/O; use LaGrange datasheet for external interfaces.'])
context('memory_module_analogue::kingston::KVR24R17D4-32','host_rdimm_analogue','Illustrative Kingston 32GB DDR4-2400 ECC RDIMM','Kingston','KVR24R17D4/32','Illustrates a removable host-memory module in the supported DDR4 RDIMM class.','DRAM components store host data; register buffers command/address traffic; SPD describes module organization.',['36 x4 DRAM packages','register','SPD/temperature device','288 gold contact fingers','keyed PCB'],[doc('kingston-kvr24r17d4-32',1),doc('kingston-kvr24r17d4-32',2),source(SPEC,page_1based=18)],{'pcb_length_mm':133.35,'pcb_height_mm':31.25,'key_center_from_left_mm':72.25,'key_width_mm':1.5,'key_width_tolerance_mm':0.1},['Manufacturer example only: no evidence this exact module ships in selected EVT assembly.','Drawing front/back chip arrangement is reference illustration; individual DRAM MPN unspecified.'])
context('thermal_sensor_context::texas-instruments::TMP75AIDR','thermal_sensor','Barreleye G2 temperature-monitoring context','Texas Instruments','TMP75AIDR','Measures inlet, outlet and HDD-area temperatures for BMC management.','Digital temperature sensors report over two-wire SMBus.',['temperature sensor','ADC','SMBus interface'],[source(SPEC,page_1based=27)],None,['Platform specification context; not located in the motherboard PWA BOM derivative.','Do not place a guessed sensor at an arbitrary coordinate. Confirm fan/backplane BOM for those boards.','Spec lists fan-board address0x72; preserve as document text, do not assume7-bit sensor address without schematic validation.'])
context('server_assembly::ocp::barreleye-g2-evt','server_assembly','Barreleye G2 EVT two-OU server','OCP / Ingrasys / Google / Rackspace',None,'Combines compute board, drives, power distribution and cooling in a serviceable chassis.','A 48V rack connection supplies board conversion and system distribution while fans move cooling air through the assembly.',['chassis','motherboard','drive backplane','fan/power distribution board','drive carriers','fans','heatsinks','harnesses'],[source(SPEC,page_1based=44),source(SPEC,page_1based=56)],None,['Server CAD revision EVT20170310 and motherboard electrical EVT3 retained separately. Dimensions from measured CAD must carry its revision.'])
context('management_context::concept::bmc-dcim-scada','management_context','Management scope: BMC, DCIM and facility SCADA',None,None,'Separates server management electronics from data-center software and facility control.','BMC is the board computer. DCIM can inventory and aggregate facility/IT information. SCADA supervises industrial/facility processes where actually installed.',['board BMC and sensors documented here','DCIM software integration not implemented','facility SCADA equipment unspecified'],[source(SPEC,page_1based=23),source(SPEC,page_1based=27)],None,['No PLC, SCADA cabinet, DCIM product or live telemetry is documented for this server; do not fabricate one.'])
enrich('88SE9235A1-NAA2C000[VER.A1]','storage_controller','Marvell 88SE9235 SATA controller','Connects the host to SATA storage interfaces.','Host PCIe transactions are translated to SATA link operations.',['host interface','SATA controllers'],[s(152)],None,['This is a board storage controller, not an identified installed drive SKU.'])
enrich('uPD720201K8-701-BAC-A','usb_controller','Renesas uPD720201 USB controller','Provides board USB connectivity from a host interface.','Controller schedules USB traffic and drives its ports.',['host interface','USB controller'],[s(4)],None,['Specific detailed controller connections need sheet-level inspection before electrical simulation.'])
enrich('TUSB2077APTR','usb_hub','TI TUSB2077A USB hub','Fans one USB upstream connection out to downstream devices.','Hub logic forwards traffic and manages downstream ports.',['hub logic','upstream port','downstream ports'],[s(151)],None,['Actual populated external ports follow connector wiring; controller capability is not exposed-port count.'])
enrich('Q54SJ12050NNDH','dc_dc_converter','Delta Q54SJ12050 48V-to-12V converter','Provides the board 12V supply from the 48V input domain.','A switching converter transforms input power and regulates the12V output.',['conversion stage','output filter','control'],[s(178)],None,['BOM lists40–60V input and600W family rating; no simulated power efficiency or load state.'])
enrich('U10-B074-260T','high_speed_connector','Amphenol high-speed cable connector','Connects the documented high-speed serial lanes to a cable assembly.','Contacts carry differential lanes and associated signals between board and cable.',['housing','contact array','retention features'],[s(166),s(167)],None,['BOM uses SAS shorthand; functional use must follow actual NVLink/OpenCAPI lane nets. Do not label the attached cable solely from connector shape.'])
THERM=OCP/'originals/zaius-barreleye-g2/HW/thermal/EVT'
context('heatsink::furukawa::HS855600-A','cpu_heatsink','Furukawa G2 CPU heatsink','Furukawa Electric','HS855600-A','Transfers processor heat to server airflow.','A contact block and pipe/fin structure spread heat over a large air-cooled surface.',['ADC10 sink base','C1100 copper block','C1100 fin assembly','retention rack','Pipe-1 x2, material label CU/W','Pipe-2 x2, material label CU/W'],[source(THERM/'G2-CPU HSK-Furukawa-HS855600.pdf',page_1based=1,drawing='HS855600-A',date='20160816')],{'base_mm':[100,91],'base_dim_tolerance_mm':0.2,'height_max_mm':68.2,'contact_patch_mm':[70,70],'fin_stack_width_mm':85},['Drawing supplies external assembly and material labels; internal pipe geometry/fluid details not modeled from inference.','Number of fins not explicitly dimensioned; use CAD or counted resolved drawing evidence.'])
context('heatsink::furukawa::HS855360-C','vtm_heatsink','Furukawa Zaius VTM-1 heatsink','Furukawa Electric','HS855360-C','Removes heat from a pair of VTM devices.','Pads couple each module to an aluminum fin body retained by spring push-pins.',['A6063 cooler body','PCS-TC-11 pads x2','copper push-pins x2','wedges x2','springs as illustrated'],[source(THERM/'Zaius-VTM-1-HS855360-C.pdf',page_1based=1,drawing='HS855360-C',date='20160811')],{'body_mm':[80,40,25],'body_dim_tolerance_mm':0.3,'base_thickness_mm':3,'pad_size_mm':[23,23],'pushpin_centers_mm':27,'pushpin_center_tolerance_mm':0.1,'fin_dimensions_as_drawn_mm':[1.5,1.49]},['Drawing notes5lbf compressive force per chipset,4.5mm chipset height and3mm motherboard height; these are design notes, not validated applied forces.'])
context('heatsink::furukawa::HS855370-C','vtm_heatsink','Furukawa Zaius VTM-2 heatsink','Furukawa Electric','HS855370-C','Removes heat from a longer VTM device group.','An aluminum fin body contacts a pad and is retained with spring push-pins.',['A6063 cooler body','PCS-TC-11 pad','copper push-pins x2','wedges x2','springs as illustrated'],[source(THERM/'Zaius-VTM-2-HS855370-C.pdf',page_1based=1,drawing='HS855370-C',date='20160811')],{'body_mm':[80,57.3,32.6],'body_dim_tolerance_mm':0.3,'base_thickness_mm':3,'pad_size_mm':[79,22.5],'pushpin_centers_mm':70.3,'pushpin_center_tolerance_mm':0.1,'fin_dimensions_as_drawn_mm':[1.5,1.49]},['Drawing notes5lbf compressive force per chipset; not validated applied force.'])

instances={}
for p in placements:
 candidates=[by_mpn[x['manufacturer_part']] for x in p['bom_candidates'] if x['manufacturer_part'] in by_mpn]
 instances[p['refdes']]={'component_keys':sorted(set(candidates)),'population_status':p['population_status'],'listed_in_depop':p['listed_in_depop'],'source':source(PLAC,refdes=p['refdes']),'package_index':p['package_index'],'native_eda_origin_mm':[p['x_mm'],p['y_mm']],'native_eda_rotation_deg':p['rotation_odb_deg'],'native_eda_mirror':p['mirror_odb'],'side':p['side'],'height_eda_envelope_mm':p.get('height_eda_mm'),'origin_warning':'Native EDA coordinate; no scene placement or bottom-side transform implied.'}
# Preserve missing J110 height; record a traceable optional same-part reconstruction.
siblings=[p for p in placements if p['refdes']!='J110' and p.get('height_eda_mm') is not None and p['package_index']==81 and any(b['manufacturer_part']=='ASP-195607-01' for b in p['bom_candidates'])]
if 'J110' in instances and siblings and len({round(p['height_eda_mm'],6) for p in siblings})==1:
 instances['J110']['geometry_candidate']={'height_mm':siblings[0]['height_eda_mm'],'status':'supported_reconstruction_candidate_not_original_attribute','basis':'35 other placements have identical BOM MPN ASP-195607-01, package index81 and source VALUE; each has this EDA height.','source_refdes':[p['refdes'] for p in siblings],'original_height_remains':None,'limitation':'No independent custom manufacturer drawing acquired; applying candidate is an integrator decision.'}

# Keys track immutable identity; semantic_type can be refined without breaking earlier links.
for x in lib.values():
 x['refdes']=sorted(set(x['refdes']))
 x['evidence_level']['identity']=x['evidence_level']['identity'].replace('EVТ','EVT')
out={'schema_version':'1.0','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'Source-linked Zaius/Barreleye G2 EVT3 component knowledge, not certified engineering twin','key_policy':'component_key = initial semantic category::manufacturer slug::exact BOM MPN; do not parse display names as identity','units':'mm for numeric geometry unless field states otherwise','revision_policy':'EVT3 identity/population from matching BOM and ODB. Later platform specification supplies context with differences retained.','source_inputs':[{'path':rel(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [BOM,PLAC,SCH,SPEC,WB]],'components':lib,'instances_by_refdes':instances,'rights_register':rel(R/'source-register.jsonl'),'not_implemented':['Live telemetry','Electrical simulation','Robotics dynamics','AR device acceptance','Exact proprietary transistor layout']}
(ROOT/'source/component-library.json').write_text(json.dumps(out,indent=2)+'\n')
print('components',len(lib),'instances',len(instances),'enriched',sum(x['evidence_level']['function']=='documented_board_or_manufacturer' for x in lib.values()))
