'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoundedBoxGeometry } from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import { Slider } from '@/components/ui/slider';
const parts = [
 ['Front grille','Observed','Perforated protective face, with a small badge near the lower edge.'],
 ['Cabinet','Observed','Tall, softly rounded enclosure. Depth and rear geometry are approximated from this view.'],
 ['Driver assembly','Inferred','Illustrative woofer and tweeter. The photo does not reveal the actual internal configuration.'],
 ['Hanging bracket','Observed','U-shaped support with side pivot knobs for aiming the speaker.'],
 ['Wall mount','Observed','Cantilever arm, mounting plate, six fasteners, and a routed cable.']
];
export default function Page(){
 const host=useRef<HTMLDivElement>(null);const api=useRef<any>(null);
 const [amount,setAmount]=useState(35),[mode,setMode]=useState('holo'),[selected,setSelected]=useState(0),[spin,setSpin]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(!host.current)return; const el=host.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setError('WebGL is unavailable. Open this screen in a browser with hardware acceleration enabled.');return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);renderer.setClearColor(0x050d14,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(7,3.4,10);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,.25,0);controls.minDistance=5;controls.maxDistance=22;controls.autoRotateSpeed=.65;
 scene.add(new THREE.HemisphereLight(0xbbeeff,0x13212d,3));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(3,6,6);scene.add(key);const rim=new THREE.DirectionalLight(0x28dfff,5);rim.position.set(-4,2,-3);scene.add(rim);
 const root=new THREE.Group();scene.add(root);const groups=parts.map((_,i)=>{let g=new THREE.Group();g.userData.index=i;root.add(g);return g});const surfaces:THREE.Mesh[]=[];const edges:THREE.LineSegments[]=[];
 const pale=new THREE.MeshStandardMaterial({color:0xd4d0bf,roughness:.65,metalness:.12});const dark=new THREE.MeshStandardMaterial({color:0x262c2f,roughness:.8});const metal=new THREE.MeshStandardMaterial({color:0x9caeb5,metalness:.8,roughness:.28});
 function mesh(g:THREE.Group,geo:THREE.BufferGeometry,pos:number[],mat=pale){let m=new THREE.Mesh(geo,mat.clone());m.position.set(...pos as [number,number,number]);m.userData.index=g.userData.index;m.userData.original=mat.clone();g.add(m);surfaces.push(m);let e=new THREE.LineSegments(new THREE.EdgesGeometry(geo,30),new THREE.LineBasicMaterial({color:0x67eaff,transparent:true,opacity:.55}));m.add(e);edges.push(e);return m;}
 function box(g:THREE.Group,w:number,h:number,d:number,p:number[],mat=pale,r=.045){return mesh(g,new RoundedBoxGeometry(w,h,d,3,r),p,mat)}
 // Hollow cabinet shell, with front towards +Z.
 box(groups[1],.13,3.5,1.2,[-.97,0,0]);box(groups[1],.13,3.5,1.2,[.97,0,0]);box(groups[1],2.05,.14,1.2,[0,1.7,0]);box(groups[1],2.05,.14,1.2,[0,-1.7,0]);box(groups[1],2.05,3.35,.12,[0,0,-.57]);
 box(groups[0],1.94,3.32,.08,[0,0,.66],metal);const textureCanvas=document.createElement('canvas');textureCanvas.width=64;textureCanvas.height=64;const ctx=textureCanvas.getContext('2d')!;ctx.fillStyle='#b6b3a7';ctx.fillRect(0,0,64,64);ctx.fillStyle='#24292a';for(let y=0;y<64;y+=8)for(let x=0;x<64;x+=8){ctx.beginPath();ctx.arc(x+(y%16?4:0),y,2.3,0,7);ctx.fill()}const tex=new THREE.CanvasTexture(textureCanvas);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(9,16);const grille=surfaces[surfaces.length-1];(grille.material as THREE.MeshStandardMaterial).map=tex;(grille.userData.original as THREE.MeshStandardMaterial).map=tex;
 box(groups[0],.28,.15,.035,[0,-1.19,.724],dark,.015);
 box(groups[2],1.79,3.16,.12,[0,0,.43],dark);function speaker(y:number,r:number){let ring=mesh(groups[2],new THREE.TorusGeometry(r,.045,12,64),[0,y,.54],metal);const cone=mesh(groups[2],new THREE.ConeGeometry(r*.94,.22,64,1,true),[0,y,.56],dark);cone.rotation.x=Math.PI/2;const cap=mesh(groups[2],new THREE.SphereGeometry(r*.3,24,16),[0,y,.63],dark);cap.scale.z=.45;}
 speaker(-.55,.7);speaker(.93,.32);
 box(groups[3],2.5,.13,.25,[0,2.22,-.02]);box(groups[3],.13,2.38,.25,[-1.19,1.08,-.02]);box(groups[3],.13,2.38,.25,[1.19,1.08,-.02]);for(const x of [-1.29,1.29]){const m=mesh(groups[3],new THREE.CylinderGeometry(.14,.14,.2,24),[x,-.04,0],dark);m.rotation.z=Math.PI/2;}
 box(groups[4],.22,.24,1.9,[0,2.19,-.93]);box(groups[4],.84,.95,.12,[0,2.16,-1.93],metal);for(const x of [-.29,.29])for(const y of [1.81,2.16,2.51]){let m=mesh(groups[4],new THREE.CylinderGeometry(.055,.055,.04,12),[x,y,-1.85],metal);m.rotation.x=Math.PI/2;}
 const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(.12,1.5,-.62),new THREE.Vector3(.17,2.3,-.6),new THREE.Vector3(.17,2.3,-1.7),new THREE.Vector3(.4,.7,-1.8),new THREE.Vector3(.28,.2,-1.82)]);mesh(groups[4],new THREE.TubeGeometry(curve,48,.033,8,false),[0,0,0],dark);
 const grid=new THREE.GridHelper(18,36,0x245260,0x102a37);grid.position.y=-2.5;scene.add(grid);for(const radius of [2.5,2.6,3.6]){const ring=new THREE.Mesh(new THREE.RingGeometry(radius,radius+.012,120),new THREE.MeshBasicMaterial({color:0x288f9e,side:THREE.DoubleSide,transparent:true,opacity:.45}));ring.rotation.x=-Math.PI/2;ring.position.y=-2.48;scene.add(ring)}
 const labelEls=groups.map((g,i)=>{const n=document.createElement('button');n.className='part-marker';n.textContent=String(i+1).padStart(2,'0');n.setAttribute('aria-label',parts[i][0]);n.onclick=()=>setSelected(i);el.appendChild(n);return n});
 const destinations=[[0,0,2.4],[0,0,-.45],[0,0,1.15],[0,1.3,0],[0,1.4,-1.65]];let target=.35,current=.35,active=0,holo=true;
 function style(){surfaces.forEach(m=>{const mat=m.material as THREE.MeshStandardMaterial;const original=m.userData.original as THREE.MeshStandardMaterial;mat.color.copy(holo?new THREE.Color(m.userData.index===active?0x42d8ed:0x177e94):original.color);mat.map=holo?null:original.map;mat.transparent=holo;mat.opacity=holo?(m.userData.index===active?.3:.14):1;mat.depthWrite=!holo;mat.metalness=holo?.45:original.metalness;mat.roughness=holo?.3:original.roughness;mat.emissive.set(holo?0x074853:0);mat.needsUpdate=true;});edges.forEach(e=>{(e.material as THREE.LineBasicMaterial).opacity=holo?.78:.12})}
 api.current={explode:(v:number)=>target=v/100,mode:(m:string)=>{holo=m==='holo';style()},select:(v:number)=>{active=v;style()},spin:(v:boolean)=>controls.autoRotate=v,reset:()=>{camera.position.set(7,3.4,10);controls.target.set(0,.25,0)}};style();
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();let frame=0;const v=new THREE.Vector3();const anchors=[new THREE.Vector3(.8,.8,.7),new THREE.Vector3(-1,-.8,0),new THREE.Vector3(.7,-.4,.7),new THREE.Vector3(1.2,1.7,0),new THREE.Vector3(.4,2.2,-1.7)];
 const ray=new THREE.Raycaster();let down=[0,0];renderer.domElement.onpointerdown=e=>down=[e.clientX,e.clientY];renderer.domElement.onpointerup=e=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const b=el.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects(surfaces)[0];if(hit)setSelected(hit.object.userData.index)};
 function tick(){frame=requestAnimationFrame(tick);current+=(target-current)*.075;groups.forEach((g,i)=>{g.position.set(destinations[i][0]*current,destinations[i][1]*current,destinations[i][2]*current);v.copy(anchors[i]).add(g.position).project(camera);labelEls[i].style.transform=`translate(${(v.x*.5+.5)*el.clientWidth}px,${(-v.y*.5+.5)*el.clientHeight}px)`;labelEls[i].dataset.active=String(i===active)});controls.update();renderer.render(scene,camera)}tick();return()=>{cancelAnimationFrame(frame);ro.disconnect();controls.dispose();surfaces.forEach(m=>{m.geometry.dispose();(m.material as THREE.Material).dispose()});tex.dispose();renderer.dispose();el.innerHTML='';api.current=null};
 },[]);
 useEffect(()=>{api.current?.explode(amount)},[amount]);useEffect(()=>{api.current?.mode(mode)},[mode]);useEffect(()=>{api.current?.select(selected)},[selected]);useEffect(()=>{api.current?.spin(spin)},[spin]);
 return <main><header><a className="brand" href="/">◈ <span>ASSEMBLY<span className="muted"> / LAB</span></span></a><span className="top-note">SINGLE-IMAGE RECONSTRUCTION</span><span className="live"><i/> INTERACTIVE 3D</span></header><div className="workspace"><section className="viewport"><div className="title"><div className="eyebrow">OBJECT 001 / AUDIO</div><h1>Wall-mounted<br/>speaker.</h1><p>Form, structure, and the space between.</p></div><div className="view-tabs"><button className={mode==='holo'?'on':''} onClick={()=>setMode('holo')}>Hologram</button><button className={mode==='solid'?'on':''} onClick={()=>setMode('solid')}>Material</button></div><div ref={host} className="canvas"/>{error&&<div className="error">{error}</div>}<div className="viewport-footer"><span>DRAG TO ORBIT · SCROLL TO ZOOM · CLICK A PART</span><button onClick={()=>api.current?.reset()}>↗ Reset view</button></div><div className="axis">Y ↑<br/>Z ↙ └ → X</div></section><aside><div className="panel-heading"><span>ASSEMBLY EXPLORER</span><span>05 PARTS</span></div><section className="explode"><div className="row"><h2>Pull it apart</h2><span className="value">{amount}<small>%</small></span></div><Slider aria-label="Explode assembly" value={[amount]} onValueChange={v=>setAmount(Array.isArray(v)?v[0]:v)} min={0} max={100}/><div className="range-label"><span>Assembled</span><span>Exploded</span></div><div className="actions"><button onClick={()=>setAmount(amount>0?0:100)}>{amount>0?'↓ Assemble':'↑ Explode'}</button><button aria-pressed={spin} onClick={()=>setSpin(!spin)}>{spin?'Ⅱ Pause orbit':'⟳ Auto orbit'}</button></div></section><section className="parts">{parts.map((p,i)=><button key={p[0]} className={'part '+(selected===i?'selected':'')} onClick={()=>setSelected(i)}><span className="number">0{i+1}</span><span>{p[0]}<small className={p[1]==='Inferred'?'inferred':''}>{p[1]}</small></span><span className="arrow">↗</span></button>)}</section><section className="detail"><div className="eyebrow">SELECTED COMPONENT / 0{selected+1}</div><h2>{parts[selected][0]}</h2><p>{parts[selected][2]}</p></section><section className="reference"><img src="/reference.jpeg" alt="Source photo of the wall-mounted speaker"/><div><div className="eyebrow">SOURCE FRAME</div><strong>IMG_7961</strong><p>Approximate proportions.<br/>Not a measured CAD model.</p></div></section></aside></div><footer><span><b>●</b> Observed exterior <em>●</em> Inferred internals</span><span>RECONSTRUCTION STUDY — 01</span></footer></main>
}
